python3 ./main.py send-post eMacsLover '#UtahTech'
python3 ./main.py send-post eMacsLover '#WorkingOnSocialNetworksProject'
python3 ./main.py send-post BigOLover 'Enjoying some quiet time.'
python3 ./main.py send-post BigOLover 'Feeling accomplished!'
python3 ./main.py send-post HouseBuilder '#ProgrammingCompetition'
python3 ./main.py send-post HouseBuilder '#WordleIsAmazing'
python3 ./main.py send-post AppleVisionUser '#AtTheSmith'
python3 ./main.py send-post AppleVisionUser 'Spent the evening stargazing.'
python3 ./main.py send-post Sweetheart 'weekend getaway.'
python3 ./main.py send-post Sweetheart 'Feeling grateful.'
python3 ./main.py send-post ACMLover 'Setting goals for the future.'
python3 ./main.py send-post ACMLover 'Just finished an amazing book!'
python3 ./main.py send-post AngelWarlock 'Feeling accomplished!'
python3 ./main.py send-post AngelWarlock 'Enjoying some quiet time.'
python3 ./main.py send-post AssassinTitan 'Power of kindness.'
python3 ./main.py send-post AssassinTitan '#concert.'
python3 ./main.py send-post BeastConqueror '#Zonos'
python3 ./main.py send-post BeastConqueror 'Feeling grateful.'
python3 ./main.py send-post BigOLover '#birthday'
python3 ./main.py send-post BigOLover '#winterfun'
python3 ./main.py send-post BlazingAssassin 'Savoring the little moments.'
python3 ./main.py send-post BlazingAssassin '#selfcare'
python3 ./main.py send-post CelestialDestroyer '#B-Tree'
python3 ./main.py send-post CelestialDestroyer 'Feeling motivated.'
python3 ./main.py send-post ChampionSamurai 'Taking a break from Turtle.'
python3 ./main.py send-post ChampionSamurai 'Trying out a new restaurant.'
python3 ./main.py send-post ChaosGuardian 'Just adopted a new pet.'
python3 ./main.py send-post ChaosGuardian 'Computer science!'
python3 ./main.py send-post ConquerorDragon 'New blog post is up! #LookNow'
python3 ./main.py send-post ConquerorDragon 'Enjoying a lazy Sunday morning.'
python3 ./main.py send-post CosmicHunter '#movienight'
python3 ./main.py send-post CosmicHunter 'Exciting news.'
python3 ./main.py send-post CyborgAssassin 'relaxing spa day!'
python3 ./main.py send-post CyborgAssassin 'Heading to the beach.'
python3 ./main.py send-post DemonWarrior 'Announced an upcoming project!'
python3 ./main.py send-post DemonWarrior '#Paxos'
python3 ./main.py send-post DestroyerSorcerer '#entertainment'
python3 ./main.py send-post DestroyerSorcerer '#proud'
python3 ./main.py send-post DivinePirate '#metime'
python3 ./main.py send-post DivinePirate 'relaxing spa day!'
python3 ./main.py send-post DragonSorcerer '#B-Tree'
python3 ./main.py send-post DragonSorcerer '#birthday'
python3 ./main.py send-post EnigmaTitan '#fitness'
python3 ./main.py send-post EnigmaTitan '#party'
python3 ./main.py send-post EternalChampion 'Trying out a new recipe tonight.'
python3 ./main.py send-post EternalChampion '#weekendvibes'
python3 ./main.py send-post FierceWarrior 'passions for life!'
python3 ./main.py send-post FierceWarrior '#shopping'
python3 ./main.py send-post FierySamurai '#UndergraduateResearch#HaileyAndHaleyIsTheBest'
python3 ./main.py send-post FierySamurai 'Looking forward to the weekend.'
python3 ./main.py send-post FrozenViking 'New blog post is up! #LookNow'
python3 ./main.py send-post FrozenViking '#AtTheSmith'
python3 ./main.py send-post GhostNinja '#BaconNumber'
python3 ./main.py send-post GhostNinja '#culture'
python3 ./main.py send-post GladiatorGhost '#inspired'
python3 ./main.py send-post GladiatorGhost 'Starting a new chapter.'
python3 ./main.py send-post GoldenLegend 'Spent the day exploring a city.'
python3 ./main.py send-post GoldenLegend '#familytime'
python3 ./main.py send-post BeastConqueror '#blessed'
python3 ./main.py send-post BeastConqueror 'Attended a lecture.'
python3 ./main.py send-post BlazingAssassin 'weekend getaway.'
python3 ./main.py send-post BlazingAssassin '#ILoveSudoku'
python3 ./main.py send-post CelestialDestroyer '#movienight'
python3 ./main.py send-post CelestialDestroyer 'Heading out for a hike.'
python3 ./main.py send-post ChaosGuardian '#shopping'
python3 ./main.py send-post ChaosGuardian 'Just finished an amazing book!'
python3 ./main.py send-post CosmicHunter '#inspired'
python3 ./main.py send-post CosmicHunter '#Paxos'
python3 ./main.py send-post CyborgAssassin '#bookworm'
python3 ./main.py send-post CyborgAssassin 'Enjoying some quiet time.'
python3 ./main.py send-post DemonWarrior 'Heading out for a hike.'
python3 ./main.py send-post DemonWarrior '#BaconNumber'
python3 ./main.py send-post EnigmaTitan0 'Taking a break from Turtle.'
python3 ./main.py send-post EnigmaTitan0 'Enjoying a lazy Sunday morning.'
python3 ./main.py send-post EternalChampion2 '#selfcare'
python3 ./main.py send-post EternalChampion2 '#WordleIsAmazing'
python3 ./main.py send-post FierceWarrior4 '#party'
python3 ./main.py send-post FierceWarrior4 'Just adopted a new pet.'
python3 ./main.py send-post FierySamurai '#Programming'
python3 ./main.py send-post FierySamurai 'New blog post is up! #LookNow'
python3 ./main.py send-post FrozenViking0 '#movienight'
python3 ./main.py send-post FrozenViking0 '#Coffee'
python3 ./main.py send-post GhostNinja 'Shine bright like a diamond'
python3 ./main.py send-post GhostNinja 'Spent the day exploring a city.'
python3 ./main.py send-post GuardianPhoenix '#blessed'
python3 ./main.py send-post GuardianPhoenix 'Feeling motivated.'
python3 ./main.py send-post HeroBeast 'positive mindset'
python3 ./main.py send-post HeroBeast '#Paxos'
python3 ./main.py send-post HunterGladiator 'Spent the evening stargazing.'
python3 ./main.py send-post HunterGladiator 'Savoring the little moments.'
python3 ./main.py send-post InfernoRogue432 'Starting a new chapter.'
python3 ./main.py send-post InfernoRogue432 'Starting a new chapter.'
python3 ./main.py send-post InfernoRogue 'Attended motivational seminar.'
python3 ./main.py send-post InfernoRogue '#fitness'
python3 ./main.py send-post InfinitePhantom '#selfcare'
python3 ./main.py send-post InfinitePhantom 'Adventure awaits!'
python3 ./main.py send-post KnightRogue '#travel'
python3 ./main.py send-post KnightRogue '#blessed'
python3 ./main.py send-post LegendMage 'weekend getaway.'
python3 ./main.py send-post LegendMage 'Celebrating a milestone.'
python3 ./main.py send-post LegendMage634 'Had a blast at the concert.'
python3 ./main.py send-post LegendMage634 '#starrynight'
python3 ./main.py send-post LunarAngel 'weekend getaway.'
python3 ./main.py send-post LunarAngel 'relaxing spa day!'
python3 ./main.py send-post MageWizard '#UtahTech'
python3 ./main.py send-post MageWizard 'Russ is amazing!'
python3 ./main.py send-post MagicalConqueror 'New blog post is up! #LookNow'
python3 ./main.py send-post MagicalConqueror 'weekend getaway.'
python3 ./main.py send-post MasterAssassin 'Enjoying a lazy Sunday morning.'
python3 ./main.py send-post MasterAssassin '#Coffee'
python3 ./main.py send-post MightyCyborg '#CS4307'
python3 ./main.py send-post MightyCyborg 'Cooking up in the kitchen.'
python3 ./main.py send-post MysticWizard 'Catching up with friends.'
python3 ./main.py send-post MysticWizard 'cup of coffee.'
python3 ./main.py send-post NeonBeast '#volunteering #givingback'
python3 ./main.py send-post NeonBeast '#boardgames'
python3 ./main.py send-post NinjaShogun5 'Just hit the gym. #fitnessgoals'
python3 ./main.py send-post NinjaShogun5 '#Programming'
python3 ./main.py send-post NinjaShogun 'Announced an upcoming project!'
python3 ./main.py send-post NinjaShogun 'Exciting news.'
python3 ./main.py send-post PhantomGladiator '#BaconNumber'
python3 ./main.py send-post PhantomGladiator '#B-Tree'
python3 ./main.py send-post PhoenixMage34 'Feeling energized.'
python3 ./main.py send-post PhoenixMage34 'Power of kindness.'
python3 ./main.py send-post PirateRogue 'cup of coffee.'
python3 ./main.py send-post PirateRogue '#culture'
python3 ./main.py send-post RadiantGhost123 '#Golden'
python3 ./main.py send-post RadiantGhost123 'Savoring the little moments.'
python3 ./main.py send-post RogueHunter421 '#DistributedSystemsBestClass'
python3 ./main.py send-post RogueHunter421 '#bookworm'
python3 ./main.py send-post SavageHero 'Learning so much!'
python3 ./main.py send-post SavageHero 'Enjoying a beautiful sunset.'
python3 ./main.py send-post SavageHero '#birthday'
python3 ./main.py send-post SavageHero '#starrynight'
python3 ./main.py send-post TitanWizards '#DistributedSystemsBestClass'
python3 ./main.py send-post TitanWizards '#bookworm'
python3 ./main.py send-post TitanWizard '#BaconNumber'
python3 ./main.py send-post TitanWizard 'Invision!'
python3 ./main.py send-post Vpirate 'New blog post is up! #LookNow'
python3 ./main.py send-post Vpirate 'night in the town.'
python3 ./main.py send-post PirateViking 'Savoring the little moments.'
python3 ./main.py send-post PirateViking '#Programming'
python3 ./main.py send-post Warunter 'Taking a break from Turtle.'
python3 ./main.py send-post Warunter 'Getting lost in a novel.'
python3 ./main.py send-post WarlockHunter '#winterfun'
python3 ./main.py send-post WarlockHunter '#shopping'
python3 ./main.py send-post WarriorKnight '#starrynight'
python3 ./main.py send-post WarriorKnight 'Attended a lecture.'
