python3 ./main.py add-account russross@vim.com eMacsLover
python3 ./main.py add-account curtislarsen@emacs.com BigOLover
python3 ./main.py add-account bartstander@thonny.com HouseBuilder
python3 ./main.py add-account loraklein@vscode.com AppleVisionUser
python3 ./main.py add-account mattkearl@vscode.com Sweetheart
python3 ./main.py add-account carolstander@thonny.com ACMLover
python3 ./main.py add-account rennquinn@vim.com AngelWarlock
python3 ./main.py add-account john.doe@example.com AssassinTitan
python3 ./main.py add-account jane.smith@example.com BeastConqueror
python3 ./main.py add-account bob.jones@example.com BigOLover
python3 ./main.py add-account emily.wilson@example.com BlazingAssassin
python3 ./main.py add-account michael.brown@example.com CelestialDestroyer
python3 ./main.py add-account sarah.williams@example.com ChampionSamurai
python3 ./main.py add-account david.taylor@example.com ChaosGuardian
python3 ./main.py add-account lisa.martin@example.com ConquerorDragon
python3 ./main.py add-account kevin.anderson@example.com CosmicHunter
python3 ./main.py add-account amanda.thomas@example.com CyborgAssassin
python3 ./main.py add-account steve.jackson@example.com DemonWarrior
python3 ./main.py add-account karen.white@example.com DestroyerSorcerer
python3 ./main.py add-account ryan.moore@example.com DivinePirate
python3 ./main.py add-account jessica.hall@example.com DragonSorcerer
python3 ./main.py add-account matthew.young@example.com EnigmaTitan
python3 ./main.py add-account ashley.lee@example.com EternalChampion
python3 ./main.py add-account daniel.clark@example.com FierceWarrior
python3 ./main.py add-account melissa.roberts@example.com FierySamurai
python3 ./main.py add-account brian.harris@example.com FrozenViking
python3 ./main.py add-account laura.lewis@example.com GhostNinja
python3 ./main.py add-account chris.walker@example.com GladiatorGhost
python3 ./main.py add-account kimberly.hill@example.com GoldenLegend
python3 ./main.py add-account james.allen@example.com BeastConqueror
python3 ./main.py add-account tiffany.green@example.com BlazingAssassin
python3 ./main.py add-account adam.carter@example.com CelestialDestroyer
python3 ./main.py add-account natalie.edwards@example.com ChaosGuardian
python3 ./main.py add-account robert.phillips@example.com CosmicHunter
python3 ./main.py add-account stephanie.cook@example.com CyborgAssassin
python3 ./main.py add-account peter.rogers@example.com DemonWarrior
python3 ./main.py add-account angela.bell@example.com EnigmaTitan0
python3 ./main.py add-account mark.ward@example.com EternalChampion2
python3 ./main.py add-account christina.wood@example.com FierceWarrior4
python3 ./main.py add-account patrick.collins@example.com FierySamurai
python3 ./main.py add-account heather.stewart@example.com FrozenViking0
python3 ./main.py add-account justin.murphy@example.com GhostNinja
python3 ./main.py add-account katie.ross@example.com GuardianPhoenix
python3 ./main.py add-account jonathan.howard@example.com HeroBeast
python3 ./main.py add-account jennifer.alexander@example.com HunterGladiator
python3 ./main.py add-account nathan.nelson@example.com InfernoRogue432
python3 ./main.py add-account samantha.campbell@example.com InfernoRogue
python3 ./main.py add-account dennis.richards@example.com InfinitePhantom
python3 ./main.py add-account brittany.ross@example.com KnightRogue
python3 ./main.py add-account gregory.harrison@example.com LegendMage
python3 ./main.py add-account stephanie.brooks@example.com LegendMage634
python3 ./main.py add-account jeremy.bennett@example.com LunarAngel
python3 ./main.py add-account rebecca.wood@example.com MageWizard
python3 ./main.py add-account scott.peterson@example.com MagicalConqueror
python3 ./main.py add-account erica.ramirez@example.com MasterAssassin
python3 ./main.py add-account joshua.lee@example.com MightyCyborg
python3 ./main.py add-account courtney.morgan@example.com MysticWizard
python3 ./main.py add-account olivia.garcia@example.com NeonBeast
python3 ./main.py add-account dylan.flores@example.com NinjaShogun5
python3 ./main.py add-account madison.young@example.com NinjaShogun
python3 ./main.py add-account ethan.wilson@example.com PhantomGladiator
python3 ./main.py add-account hannah.gonzalez@example.com PhoenixMage34
python3 ./main.py add-account andrew.hall@example.com PirateRogue
python3 ./main.py add-account isabella.nelson@example.com RadiantGhost123
python3 ./main.py add-account jacob.richardson@example.com RogueHunter421
python3 ./main.py add-account ava.carter@example.com SavageHero
python3 ./main.py add-account william.mitchell@example.com SavageHero
python3 ./main.py add-account sophia.perez@example.com TitanWizards
python3 ./main.py add-account noah.roberts@example.com TitanWizard
python3 ./main.py add-account mia.ramirez@example.com Vpirate
python3 ./main.py add-account logan.cooper@example.com PirateViking
python3 ./main.py add-account amelia.howard@example.com Warunter
python3 ./main.py add-account james.collins@example.com WarlockHunter
python3 ./main.py add-account emma.kelly@example.com WarriorKnight
