python3 ./main.py add-user russross@vim.com
python3 ./main.py add-user curtislarsen@emacs.com
python3 ./main.py add-user bartstander@thonny.com
python3 ./main.py add-user loraklein@vscode.com
python3 ./main.py add-user mattkearl@vscode.com
python3 ./main.py add-user carolstander@thonny.com
python3 ./main.py add-user rennquinn@vim.com
python3 ./main.py add-user john.doe@example.com
python3 ./main.py add-user jane.smith@example.com
python3 ./main.py add-user bob.jones@example.com
python3 ./main.py add-user emily.wilson@example.com
python3 ./main.py add-user michael.brown@example.com
python3 ./main.py add-user sarah.williams@example.com
python3 ./main.py add-user david.taylor@example.com
python3 ./main.py add-user lisa.martin@example.com
python3 ./main.py add-user kevin.anderson@example.com
python3 ./main.py add-user amanda.thomas@example.com
python3 ./main.py add-user steve.jackson@example.com
python3 ./main.py add-user karen.white@example.com
python3 ./main.py add-user ryan.moore@example.com
python3 ./main.py add-user jessica.hall@example.com
python3 ./main.py add-user matthew.young@example.com
python3 ./main.py add-user ashley.lee@example.com
python3 ./main.py add-user daniel.clark@example.com
python3 ./main.py add-user melissa.roberts@example.com
python3 ./main.py add-user brian.harris@example.com
python3 ./main.py add-user laura.lewis@example.com
python3 ./main.py add-user chris.walker@example.com
python3 ./main.py add-user kimberly.hill@example.com
python3 ./main.py add-user james.allen@example.com
python3 ./main.py add-user tiffany.green@example.com
python3 ./main.py add-user adam.carter@example.com
python3 ./main.py add-user natalie.edwards@example.com
python3 ./main.py add-user robert.phillips@example.com
python3 ./main.py add-user stephanie.cook@example.com
python3 ./main.py add-user peter.rogers@example.com
python3 ./main.py add-user angela.bell@example.com
python3 ./main.py add-user mark.ward@example.com
python3 ./main.py add-user christina.wood@example.com
python3 ./main.py add-user patrick.collins@example.com
python3 ./main.py add-user heather.stewart@example.com
python3 ./main.py add-user justin.murphy@example.com
python3 ./main.py add-user katie.ross@example.com
python3 ./main.py add-user jonathan.howard@example.com
python3 ./main.py add-user jennifer.alexander@example.com
python3 ./main.py add-user nathan.nelson@example.com
python3 ./main.py add-user samantha.campbell@example.com
python3 ./main.py add-user dennis.richards@example.com
python3 ./main.py add-user brittany.ross@example.com
python3 ./main.py add-user gregory.harrison@example.com
python3 ./main.py add-user stephanie.brooks@example.com
python3 ./main.py add-user jeremy.bennett@example.com
python3 ./main.py add-user rebecca.wood@example.com
python3 ./main.py add-user scott.peterson@example.com
python3 ./main.py add-user erica.ramirez@example.com
python3 ./main.py add-user joshua.lee@example.com
python3 ./main.py add-user courtney.morgan@example.com
python3 ./main.py add-user olivia.garcia@example.com
python3 ./main.py add-user dylan.flores@example.com
python3 ./main.py add-user madison.young@example.com
python3 ./main.py add-user ethan.wilson@example.com
python3 ./main.py add-user hannah.gonzalez@example.com
python3 ./main.py add-user andrew.hall@example.com
python3 ./main.py add-user isabella.nelson@example.com
python3 ./main.py add-user jacob.richardson@example.com
python3 ./main.py add-user ava.carter@example.com
python3 ./main.py add-user william.mitchell@example.com
python3 ./main.py add-user sophia.perez@example.com
python3 ./main.py add-user noah.roberts@example.com
python3 ./main.py add-user mia.ramirez@example.com
python3 ./main.py add-user logan.cooper@example.com
python3 ./main.py add-user amelia.howard@example.com
python3 ./main.py add-user james.collins@example.com
python3 ./main.py add-user emma.kelly@example.com
python3 ./main.py add-user benjamin.bailey@example.com
