python3 ./main.py send-post eMacsLover 'Just hit the gym. #fitnessgoals'
python3 ./main.py send-post eMacsLover '#movienight'
python3 ./main.py send-post BigOLover '#proud'
python3 ./main.py send-post BigOLover 'positive mindset'
python3 ./main.py send-post HouseBuilder '#CS4307'
python3 ./main.py send-post HouseBuilder 'Catching up with friends.'
python3 ./main.py send-post AppleVisionUser '#boardgames'
python3 ./main.py send-post AppleVisionUser 'Savoring the little moments.'
python3 ./main.py send-post Sweetheart 'Excited to meet new people!'
python3 ./main.py send-post Sweetheart '#proud'
python3 ./main.py send-post ACMLover '#party'
python3 ./main.py send-post ACMLover 'Catching up with friends.'
python3 ./main.py send-post AngelWarlock 'New blog post is up! #LookNow'
python3 ./main.py send-post AngelWarlock 'beauty of nature.'
python3 ./main.py send-post AssassinTitan 'positive mindset'
python3 ./main.py send-post AssassinTitan 'Grateful for all the followers.'
python3 ./main.py send-post BeastConqueror 'Attended a lecture.'
python3 ./main.py send-post BeastConqueror 'Spent the evening stargazing.'
python3 ./main.py send-post BigOLover '#CS4307'
python3 ./main.py send-post BigOLover '#BaconNumber'
python3 ./main.py send-post BlazingAssassin 'Enjoying a lazy Sunday morning.'
python3 ./main.py send-post BlazingAssassin 'Power of kindness.'
python3 ./main.py send-post CelestialDestroyer '#AtTheSmith'
python3 ./main.py send-post CelestialDestroyer 'Spent the evening stargazing.'
python3 ./main.py send-post ChampionSamurai '#volunteering #givingback'
python3 ./main.py send-post ChampionSamurai 'scenic hike in the mountains.'
python3 ./main.py send-post ChaosGuardian '#boardgames'
python3 ./main.py send-post ChaosGuardian 'Trying out a new recipe tonight.'
python3 ./main.py send-post ConquerorDragon '#volunteering #givingback'
python3 ./main.py send-post ConquerorDragon 'Year of growth.'
python3 ./main.py send-post CosmicHunter 'Year of growth.'
python3 ./main.py send-post CosmicHunter 'Announced an upcoming project!'
python3 ./main.py send-post CyborgAssassin 'Celebrating a milestone.'
python3 ./main.py send-post CyborgAssassin '#starrynight'
python3 ./main.py send-post DemonWarrior 'Grateful for all the followers.'
python3 ./main.py send-post DemonWarrior '#weekendvibes'
python3 ./main.py send-post DestroyerSorcerer '#Paxos'
python3 ./main.py send-post DestroyerSorcerer 'Had a blast at the concert.'
python3 ./main.py send-post DivinePirate 'Power of kindness.'
python3 ./main.py send-post DivinePirate 'Excited to meet new people!'
python3 ./main.py send-post DragonSorcerer '#travel'
python3 ./main.py send-post DragonSorcerer '#Coffee'
python3 ./main.py send-post EnigmaTitan 'weekend getaway.'
python3 ./main.py send-post EnigmaTitan 'Cooking up in the kitchen.'
python3 ./main.py send-post EternalChampion 'Just hit the gym. #fitnessgoals'
python3 ./main.py send-post EternalChampion 'Heading to the beach.'
python3 ./main.py send-post FierceWarrior 'New blog post is up! #LookNow'
python3 ./main.py send-post FierceWarrior '#WorkingOnSocialNetworksProject'
python3 ./main.py send-post FierySamurai 'Taking a break from Turtle.'
python3 ./main.py send-post FierySamurai '#boardgames'
python3 ./main.py send-post FrozenViking '#birthday'
python3 ./main.py send-post FrozenViking '#blessed'
python3 ./main.py send-post GhostNinja '#BaconNumber'
python3 ./main.py send-post GhostNinja '#UndergraduateResearch#HaileyAndHaleyIsTheBest'
python3 ./main.py send-post GladiatorGhost 'Feeling inspired.'
python3 ./main.py send-post GladiatorGhost '#ILoveSudoku'
python3 ./main.py send-post GoldenLegend 'Hitting the slopes for skiing.'
python3 ./main.py send-post GoldenLegend 'Excited to meet new people!'
python3 ./main.py send-post BeastConqueror 'Heading to the beach.'
python3 ./main.py send-post BeastConqueror 'Attended motivational seminar.'
python3 ./main.py send-post BlazingAssassin 'Trying out a new recipe tonight.'
python3 ./main.py send-post BlazingAssassin 'Getting lost in a novel.'
python3 ./main.py send-post CelestialDestroyer '#movienight'
python3 ./main.py send-post CelestialDestroyer '#volunteering #givingback'
python3 ./main.py send-post ChaosGuardian '#B-Tree'
python3 ./main.py send-post ChaosGuardian '#AtTheSmith'
python3 ./main.py send-post CosmicHunter 'Looking forward to the weekend.'
python3 ./main.py send-post CosmicHunter '#party'
python3 ./main.py send-post CyborgAssassin 'Attended a lecture.'
python3 ./main.py send-post CyborgAssassin 'Feeling grateful.'
python3 ./main.py send-post DemonWarrior '#fitness'
python3 ./main.py send-post DemonWarrior 'Feeling accomplished!'
python3 ./main.py send-post EnigmaTitan0 '#DistributedSystemsBestClass'
python3 ./main.py send-post EnigmaTitan0 'Power of kindness.'
python3 ./main.py send-post EternalChampion2 'relaxing spa day!'
python3 ./main.py send-post EternalChampion2 'Just adopted a new pet.'
python3 ./main.py send-post FierceWarrior4 '#Coffee'
python3 ./main.py send-post FierceWarrior4 'Hitting the slopes for skiing.'
python3 ./main.py send-post FierySamurai '#culture'
python3 ./main.py send-post FierySamurai '#RPCChat'
python3 ./main.py send-post FrozenViking0 'beauty of nature.'
python3 ./main.py send-post FrozenViking0 '#BaconNumber'
python3 ./main.py send-post GhostNinja 'Attended a lecture.'
python3 ./main.py send-post GhostNinja 'Year of growth.'
python3 ./main.py send-post GuardianPhoenix 'Feeling energized.'
python3 ./main.py send-post GuardianPhoenix 'Looking forward to the weekend.'
python3 ./main.py send-post HeroBeast '#TechRidge'
python3 ./main.py send-post HeroBeast 'Thank you for all the support!'
python3 ./main.py send-post HunterGladiator '#fitness'
python3 ./main.py send-post HunterGladiator '#winterfun'
python3 ./main.py send-post InfernoRogue432 'Attended motivational seminar.'
python3 ./main.py send-post InfernoRogue432 '#Coffee'
python3 ./main.py send-post InfernoRogue '#WorkingOnSocialNetworksProject'
python3 ./main.py send-post InfernoRogue 'passions for life!'
python3 ./main.py send-post InfinitePhantom 'Heading out for a hike.'
python3 ./main.py send-post InfinitePhantom 'productive work session.'
python3 ./main.py send-post KnightRogue 'Heading out for a hike.'
python3 ./main.py send-post KnightRogue '#ILoveSudoku'
python3 ./main.py send-post LegendMage 'Cooking up in the kitchen.'
python3 ./main.py send-post LegendMage '#WordleIsAmazing'
python3 ./main.py send-post LegendMage634 'Russ is amazing!'
python3 ./main.py send-post LegendMage634 'Excited to meet new people!'
python3 ./main.py send-post LunarAngel 'Shine bright like a diamond'
python3 ./main.py send-post LunarAngel '#lifelonglearner'
python3 ./main.py send-post MageWizard '#metime'
python3 ./main.py send-post MageWizard 'Cooking up in the kitchen.'
python3 ./main.py send-post MagicalConqueror '#concert.'
python3 ./main.py send-post MagicalConqueror 'Feeling inspired.'
python3 ./main.py send-post MasterAssassin 'Heading to the beach.'
python3 ./main.py send-post MasterAssassin '#party'
python3 ./main.py send-post MightyCyborg '#blessed'
python3 ./main.py send-post MightyCyborg 'Feeling accomplished!'
python3 ./main.py send-post MysticWizard 'Heading to the beach.'
python3 ./main.py send-post MysticWizard 'Russ is amazing!'
python3 ./main.py send-post NeonBeast '#lifelonglearner'
python3 ./main.py send-post NeonBeast 'Starting a new chapter.'
python3 ./main.py send-post NinjaShogun5 '#quiettime'
python3 ./main.py send-post NinjaShogun5 'relaxing spa day!'
python3 ./main.py send-post NinjaShogun '#birthday'
python3 ./main.py send-post NinjaShogun 'Excited to meet new people!'
python3 ./main.py send-post PhantomGladiator 'Year of growth.'
python3 ./main.py send-post PhantomGladiator '#boardgames'
python3 ./main.py send-post PhoenixMage34 'scenic hike in the mountains.'
python3 ./main.py send-post PhoenixMage34 '#shopping'
python3 ./main.py send-post PirateRogue '#BaconNumber'
python3 ./main.py send-post PirateRogue '#bookworm'
python3 ./main.py send-post RadiantGhost123 'Just adopted a new pet.'
python3 ./main.py send-post RadiantGhost123 '#metime'
python3 ./main.py send-post RogueHunter421 'Just hit the gym. #fitnessgoals'
python3 ./main.py send-post RogueHunter421 'Grateful for all the followers.'
python3 ./main.py send-post SavageHero 'Feeling motivated.'
python3 ./main.py send-post SavageHero 'Thank you for all the support!'
python3 ./main.py send-post SavageHero 'Year of growth.'
python3 ./main.py send-post SavageHero '#familytime'
python3 ./main.py send-post TitanWizards 'Looking forward to the weekend.'
python3 ./main.py send-post TitanWizards '#starrynight'
python3 ./main.py send-post TitanWizard '#weekendvibes'
python3 ./main.py send-post TitanWizard 'weekend getaway.'
python3 ./main.py send-post Vpirate '#Zonos'
python3 ./main.py send-post Vpirate '#party'
python3 ./main.py send-post PirateViking '#winterfun'
python3 ./main.py send-post PirateViking '#lifelonglearner'
python3 ./main.py send-post Warunter 'Exciting news.'
python3 ./main.py send-post Warunter 'Heading out for a hike.'
python3 ./main.py send-post WarlockHunter 'Cooking up in the kitchen.'
python3 ./main.py send-post WarlockHunter 'Learning so much!'
python3 ./main.py send-post WarriorKnight 'Feeling inspired.'
python3 ./main.py send-post WarriorKnight 'Starting a new chapter.'
